on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      - name: Set lowercase repo name
        run: echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          npm install -g @devcontainers/cli
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        working-directory: ${{ github.workspace }}
        run: devcontainer build --workspace-folder ${{ github.workspace }} --image-name ghcr.io/${REPO_LOWER}:latest --push true
